ecsl/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from djreservation import urls as djreservation_urls

from hotel.urls import urlpatterns as hotel_urls
from imagen.views import index
from proposal.urls import urlpatterns as proposal_urls
from register.urls import urlpatterns as profile_urls
from tshirt.urls import urlpatterns as tshirt_urls


urlpatterns = [
    url(r'^$', index),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('registration.backends.hmac.urls')),
    url(r'faq/', include('faq.urls')),
] + profile_urls + hotel_urls + tshirt_urls + djreservation_urls.urlpatterns\
    + proposal_urls

faq/urls.py
from django.conf.urls import url

from faq.views import FAQListView

urlpatterns = [
    url(r'^$', FAQListView.as_view(), name='faq_list'),
]

hotel/models.py
from decimal import Decimal

from django.db import models
from django.utils.translation import ugettext_lazy as _

# Create your models here.


class Hotel(models.Model):
    name = models.CharField(max_length=250,
                            verbose_name=_("Name"))
    description = models.TextField(verbose_name=_("Description"))
    url = models.URLField(verbose_name=_("Url"))
    contact_email = models.EmailField(default="changeme@example.com",
                                      verbose_name=_("Contact email"))

    def __str__(self):
        return self.name

    def get_room_per_floor(self):
        rooms_set = self.room_set.all().order_by('floor')
        rooms = []
        lfloor = None
        for room in rooms_set:
            if lfloor is None:
                rooms.append(room)
                lfloor = room.floor
                continue
            if lfloor != room.floor:
                yield rooms
                rooms = []
                lfloor = room.floor

            rooms.append(room)
        if rooms:
            yield rooms


class Room(models.Model):
    FLOORS = (
        (1, _('First floor')),
        (2, _('Second floor')),
        (3, _('Third floor')),
        (4, _('Fourth floor')),
        (5, _('Fifth floor')),
    )
    hotel = models.ForeignKey(Hotel, verbose_name=_("Hotel"))
    floor = models.SmallIntegerField(choices=FLOORS, default=1,
                                     verbose_name=_("Floor"))
    number = models.CharField(max_length=15, verbose_name=_("Number"))
    total_beds = models.SmallIntegerField(
        default=1, verbose_name=_("Total beds"))
    matrimonial = models.BooleanField(default=False,
                                      verbose_name=_("Matrimonial"))
    available_beds = models.SmallIntegerField(default=0,
                                              verbose_name=_("Available beds"))
    price_per_bed = models.DecimalField(max_digits=10, decimal_places=2,
                                        default=Decimal(0.0),
                                        verbose_name=_("Price per bed"))
    coin = models.CharField(max_length=10, default="$",
                            verbose_name=_("Pay in "))

    def __str__(self):
        return _("%s floor %d, room %s %s %.3f", self.hotel,
                 self.floor,
                 self.number,
                 self.coin,
                 self.price_per_bed)

imagen/models.py
from django.db import models

# Create your models here.

imagen/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'index.html')

imagen/templates/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    {# METADATA  #}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {# TITLE #}
    <title>ECSL 2017 | {% block title %}Index{% endblock %}</title>

    {# CSS #}

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">


    {% block css %}{% endblock %}
</head>
<body>
	<div class="{%block container%}container{%endblock%}">
{# NAV #}
<nav class="navbar navbar-dark bg-inverse">
    <a class="navbar-brand" href="/"><strong>ECSL 2017</strong></a>
    <ul class="nav navbar-nav">
    	
        {% if request.user.is_authenticated %}     
        
        <li ><a href="{% url 'subscribe' %}"> {% trans 'Subscribe' %} </a></li>
        <li><a href="{% url 'reservation_list' %}"> {% trans 'My reservations' %}  </a> </li>
        <li><a href="{% url 'hotel_list' %}"> {% trans 'Reserve hotel' %}  </a>
        <li><a href="{% url 'tshirt:objectview_list' %}"> {% trans 'Reserve Tshirt' %} </a>
		<li><a href="{% url 'speech:objectview_list' %}"> {% trans 'Propuse speech' %} </a>
   		</li>   
        {% else %}
            <li><a href="{% url 'registration_register' %}">{% trans 'Register' %} </a></li>
        {% endif %}
        <li><a href="{% url 'faq_list' %}">{% trans 'Common questions' %}</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
  <li role="presentation" class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
      {% trans 'User:' %} {{ request.user.get_full_name}}<span class="caret"></span>
    </a>
    	<ul class="dropdown-menu">
        {% if request.user.is_authenticated %}
       
      	  <li ><a href="{% url 'profile' %}"> {% trans 'Profile' %} </a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'auth_logout' %}">{% trans "Log out" %}</a></li>
        {% else %}
            <li class="nav-item"><a class="nav-link" href="{% url 'auth_login' %}">{% trans "Log in" %}</a></li>
        {% endif %}
       </ul>
   </li> </ul>
</nav>

{# CONTENT #}

{% if messages %}


<div class="alert alert-warning alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>

    {% for message in messages %}
   {{ message }}<br>
    {% endfor %}

</div>
{% endif %}


    {% block content %}
    {% endblock %}
</div>

{# FOOTER #}
<footer class="footer">
    <div class="container">
        <p class="text-muted"><strong>Comunidad Centroamericana de Software Libre</strong> 
    </div>
</footer>

<div class="jsmessage"></div>
{# JS #}
<script src="{% static 'js/jquery-1.10.2.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
{% block js %}{% endblock %}
</body>
</html>

imagen/templates/index.html
{% extends 'base.html' %}

{% block content %}

<div class="well">
	<h1>Encuentro centroamericano de Software Libre </h1>
</div>

{% endblock %}