ecsl/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from djreservation import urls as djreservation_urls

from hotel.urls import urlpatterns as hotel_urls
from imagen.views import index
from proposal.urls import urlpatterns as proposal_urls
from register.urls import urlpatterns as profile_urls
from tshirt.urls import urlpatterns as tshirt_urls


urlpatterns = [
    url(r'^$', index),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('registration.backends.hmac.urls')),
    url(r'faq/', include('faq.urls')),
] + profile_urls + hotel_urls + tshirt_urls + djreservation_urls.urlpatterns\
    + proposal_urls

faq/urls.py
from django.conf.urls import url

from faq.views import FAQListView

urlpatterns = [
    url(r'^$', FAQListView.as_view(), name='faq_list'),
]

register/urls.py
'''
Created on Oct 2, 2016

@author: usuario
'''
from django.conf.urls import url, include

from register.views import UpdateProfile, CreateProfile, profile_view, subscribe,\
    paypal_response

urlpatterns = [
    url(r'accounts/profile/?$', profile_view, name="profile"),
    url(r'^register/profile/create$',
        CreateProfile.as_view(), name='create_profile'),
    url(r'^register/profile/update/(?P<pk>\d+)$',  UpdateProfile.as_view(),
        name='edit_profile'),
    url(r'^register/subscribeme$', subscribe, name="subscribe"),
    url(r'register/paypal/(?P<status>\w+)$',
        paypal_response, name="paypal_ap"),
    url(r'^\/?paypal/', include('paypal.standard.ipn.urls')),
]

register/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import ugettext_lazy as _

# Create your models here.
# Create your models here.


class Profile(models.Model):
    NACIONALITIES = (
        ('PA', "Panamá"),
        ('CR', "Costa Rica"),
        ('NI', "Nicaragua"),
        ('HON', "Honduras"),
        ("SAL", "Salvador"),
        ("BEL", "Belice"),
        ("GUA", "Guatemala"),
        ("otro", _("Other nacionalities"))

    )
    GENDER = (
        (0, _('Male')),
        (1, _('Female')),
        (2, _("Other")),
    )

    user = models.OneToOneField(User,
                                verbose_name=_("User"))
    nacionality = models.CharField(
        max_length=5,
        choices=NACIONALITIES,
        verbose_name=_("Nacionality"))

    identification = models.CharField(max_length=20,
                                      verbose_name=_("Identification"))
    born_date = models.DateField(verbose_name=_("Born date"))
    gender = models.SmallIntegerField(
        choices=GENDER,
        verbose_name=_("Gender")
    )
    institution = models.CharField(max_length=250, null=True,
                                   blank=True,
                                   verbose_name=_("Institution"))
    snore = models.BooleanField(default=False,
                                verbose_name=_("Snore during sleep"))
    alimentary_restriction = models.TextField(
        null=True, blank=True,
        verbose_name=_("Alimentary restriction"))

    health_considerations = models.TextField(
        null=True, blank=True,
        verbose_name=_("Health considerations"))


class Inscription(models.Model):
    user = models.OneToOneField(User)
    preregistered = models.BooleanField(default=False,
                                        verbose_name=_("Pre-registered")
                                        )
    registered = models.BooleanField(default=False,
                                     verbose_name=_("Registered")
                                     )

    mozilla_subvention = models.BooleanField(default=False,
                                             verbose_name=_(
                                                 "Mozilla Subvention")
                                             )

    mozilla_subvention_description = models.TextField(
        null=True, blank=True,
        verbose_name=_("Why should we give you the mozilla subvention")
    )
    subvention_request = models.BooleanField(default=False,
                                             verbose_name=_(
                                                 "Subvention request")
                                             )
    subvention_description = models.TextField(
        null=True, blank=True,
        verbose_name=_("Why should we give you the subvention")
    )
    payed = models.BooleanField(default=False,
                                verbose_name=_("Payed")
                                )

    def __str__(self):
        return self.user.get_full_name()

register/forms.py
# encoding: utf-8

'''
Free as freedom will be 5/10/2016

@author: luisza
'''

from __future__ import unicode_literals

from django import forms
from django.utils.translation import ugettext_lazy as _

from register.models import Profile, Inscription


class ProfileForm(forms.ModelForm):
    first_name = forms.CharField(label=_("First name"))
    last_name = forms.CharField(label=_("Last name"))

    field_order = [
        'first_name', 'last_name',
        'identification', 'nacionalidad',
        'born_date', 'gender', 'institution'
    ]

    def __init__(self, *args, **kwargs):
        if 'instance' in kwargs and kwargs['instance']:
            perfil = kwargs['instance']
            kwargs['initial']['first_name'] = perfil.user.first_name
            kwargs['initial']['last_name'] = perfil.user.last_name

        super(ProfileForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        dev = super(ProfileForm, self).save(commit=commit)

        if self.instance:
            user = self.instance.user
            user.first_name = self.cleaned_data['first_name']
            user.last_name = self.cleaned_data['last_name']
            user.save()
        return dev

    class Meta:
        model = Profile
        fields = '__all__'
        exclude = ['user']


class InscriptionForm(forms.ModelForm):

    class Meta:
        model = Inscription
        fields = ['subvention_request', 'subvention_description',
                  'mozilla_subvention', 'mozilla_subvention_description'
                  ]

register/views.py
from datetime import datetime

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.urls.base import reverse
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.utils.translation import ugettext_lazy as _
from django.views.decorators.csrf import csrf_exempt
from django.views.generic.edit import CreateView, UpdateView

from register.forms import ProfileForm, InscriptionForm
from register.models import Profile, Inscription
from register.paypal import PaypalForm


def in_register_time():

    start_date = timezone.make_aware(
        datetime.strptime(settings.INSCRIPTION_START_DATE, '%d/%m/%Y %H:%M'),
        timezone.get_default_timezone())
    end_date = timezone.make_aware(datetime.strptime(
        settings.INSCRIPTION_END_DATE, '%d/%m/%Y %H:%M'),
        timezone.get_default_timezone())

    today = timezone.now()
    dev = False
    if start_date < today < end_date:
        dev = True
    return dev


@login_required
def subscribe(request):
    user = request.user
    success = None
    inscription = Inscription.objects.filter(user=user).first()
    if inscription and inscription.preregistered and in_register_time():
        form = PaypalForm(inscription)
        return render(request, 'register/inscription.html',
                      {'inscription': inscription,
                       'cost': settings.INSCRIPTION_COST,
                       'form': form})

    if request.method == 'POST':
        form = InscriptionForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = user
            instance.preregistered = True
            instance.save()
            success = _("Thanks, Inscription saved successfully ")
    else:
        form = InscriptionForm()
    return render(request, 'register/preinscription.html',
                  {'inscription': inscription,
                   'form': form,
                   'success': success})


@method_decorator(login_required, name='dispatch')
class CreateProfile(CreateView):
    model = Profile
    form_class = ProfileForm

    success_url = "/"

    def form_valid(self, form):
        messages.success(self.request, _('Profile created successfully'))
        form.instance.user = self.request.user
        user = self.request.user
        user.first_name = form.cleaned_data['first_name']
        user.last_name = form.cleaned_data['last_name']
        user.save()
        return super(CreateProfile, self).form_valid(form)

    def get(self, request, *args, **kwargs):
        profile = self.model.objects.filter(user=request.user)
        if len(profile):
            return redirect(reverse('edit_profile', args=(profile[0].pk,)))
        return super(CreateProfile, self).get(self, request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        profile = self.model.objects.filter(user=request.user)
        if len(profile):
            return redirect(reverse('edit_profile', args=(profile[0].pk,)))
        return CreateView.post(self, request, *args, **kwargs)


@method_decorator(login_required, name='dispatch')
class UpdateProfile(UpdateView):
    model = Profile
    form_class = ProfileForm
    success_url = "/"

    def form_valid(self, form):
        messages.success(self.request, _('Profile updated successfully'))
        return UpdateView.form_valid(self, form)


# Create your views here.
@login_required
def profile_view(request):
    try:
        profile = Profile.objects.get(user=request.user)
        return redirect(reverse('edit_profile', args=(profile.pk,)))
    except:
        return redirect(reverse('create_profile'))


@csrf_exempt
def paypal_response(request, status):
    return render(request, 'register/paypal.html', {'status': status})

register/templates/register/inscription.html
{% extends 'base.html' %}

{% load i18n %}
{% block content %}

<div class="row">
  <div class="col-md-6 col-md-offset-3">  	
  	<h1> {% trans 'Inscription details' %}</h1>
  	
  	{% if inscription.payed %}
  	<div class="alert alert-success"> {% trans 'You are registered' %}</div>
  	{% else %}
  	{% if inscription.registered %}
		<div class="alert alert-info">
			{% trans 'Already it registered at the event' %}
		</div>
		<strong> {% trans 'Mozilla subvention' %}: </strong> {{inscription.mozilla_subvention}}
		<strong> {% trans 'Subvention requested' %}: </strong> {{inscription.subvention_request}}
	  	{% else %}
	   	
	  	 	<br><br>
	  	<table class="table">
	  		<tr>
	  			<th>{% trans 'Description' %}</th>
	  			<td> {% trans 'Sign up on the ECSL' %}</td>
	  		</tr>
	  		<tr>
	  			<th>{% trans 'Subscritor' %}</th>
	  			<td> {{ inscription.user.get_full_name }}</td>
	  		</tr>
	  		
	  		<tr>
	  			<th>{% trans 'Cost' %}</th>
	  			<td> {{cost}}</td>
	  		</tr>
	  		<tr>
	  			<th> </th>
	  			<td> 	{{ form.render }}	</td>
	  		</tr>
	  		
	  	</table>
	  	
	  		  	
	  	
	  	{% endif %}
  	
  	{% endif %}
  </div>
</div>


{% endblock %}

register/templates/register/paypal.html
{% extends 'base.html' %}

{% load i18n %}
{% block content %}

<div class="well">
{% if status == 'success' %}
	<h2> {% trans 'Paypal received successfully' %}</h2>
{% else %}
	<h2> {% trans 'Sorry: Wrong Paypal notification ' %}</h2>
{%endif %}
</div>
{% endblock %}

register/templates/register/preinscription.html
{% extends 'base.html' %}
{% load bootstrap static %}
{% load i18n %}

{% block content %}

<div class="row">
  <div class="col-md-6 col-md-offset-3">  	
<div>
  <h1>{% trans 'Pre-register' %}</h1>
</div>
{% if success %}
<div class="alert alert-success" >
	{{success}}
</div>
{% else %}

{% if inscription.preregistered %}
<div class="alert alert-success" >
	{% trans _('You are pre-registered') %}
</div>
{% else %}
<div class="row">
	{% if form.errors %}
		<div class="alert alert-warning"> {{form.errors}} </div>
	{% endif %}
  <form method="post" action="">
    {% csrf_token %}
    {{ form|bootstrap  }}

    <div class="form-group">
      <button type="submit" class="btn btn-primary">{% trans 'Pre-register' %}</button>
    </div>
  </form>
</div>
{% endif %}
{% endif %}
  </div>
</div>
{% endblock %}

{% block js %}

<script>

function show_description(check, text, label){
	if($(check).is(':checked')){
	    $(text).show();  // checked
	    $(label).show();
	}else{
	    $(text).hide();  // unchecked
	    $(label).hide();
	}
}

$("#id_subvention_request").change(function(){
	show_description("#id_subvention_request", "#id_subvention_description", 
	"label[for=id_subvention_description]");
});

$("#id_mozilla_subvention").change(function(){
	show_description("#id_mozilla_subvention", "#id_mozilla_subvention_description",
"label[for=id_mozilla_subvention_description]");
});
show_description("#id_subvention_request", "#id_subvention_description", 
"label[for=id_subvention_description]");
show_description("#id_mozilla_subvention", "#id_mozilla_subvention_description",
"label[for=id_mozilla_subvention_description]");

</script>

{% endblock%}

register/templates/register/profile_form.html
{% extends 'base.html' %}
{% load bootstrap static %}
{% load i18n %}

{% block content %}

<div class="row">
  <div class="col-md-6 col-md-offset-3">  	
<div>
  <h1>{% trans 'My profile' %}</h1>
</div>

<div class="row">
  <form method="post" action="">
    {% csrf_token %}
    {{ form|bootstrap  }}

    <div class="form-group">
      <button type="submit" class="btn btn-primary">{% trans 'Save' %}</button>
    </div>
  </form>
</div>

  </div>
</div>
{% endblock %}


{% block css %}
<link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">
{% endblock %}

{% block js %}
<script type="text/javascript" src="{% static 'js/bootstrap-datepicker.js' %}"></script>
<script>
$('#id_born_date').bootstrap_datepicker({ format: "dd/mm/yyyy"});
</script>
{% endblock %}